---
title: "EV Infrastructure Geospatial Analysis"
output: html_notebook
---

import dataset from main project and filter to only PA

```{r}
ev_locations <- read_csv("data/ev_station_locations.csv") |>
  filter(!is.na(latitude), !is.na(longitude)) |>
  filter(state == "PA")

ev_locations
```

extract coordinates and make into spatial object

```{r}
library(sf)

coordinates <- ev_locations |>
  select(longitude, latitude) |>
  as.data.frame()

stations_sf <- st_as_sf(coordinates, 
                     coords = c("longitude", "latitude"), 
                     crs = 4326
                     )

stations_sf <- st_make_valid(stations_sf)

stations_sf
```

plot ev stations on US map

```{r}
library(ggplot2)
library(ggspatial)
library(rnaturalearth)
library(rnaturalearthdata)

us <- ne_countries(scale = "medium", returnclass = "sf") |>
  filter(admin == "United States of America")

ggplot(data = us) + 
  geom_sf() +
  geom_sf(data = stations_sf, color = "green", size = 0.1) +
  coord_sf(xlim = c(-81, -74), ylim = c(39, 43), expand = FALSE)

```

import census data

```{r}
library(tidycensus)

population <- get_acs(geography = "county",
                      variables = "B01003_001",
                      year = 2022,
                      geometry = TRUE)

population <- st_transform(population, st_crs(stations_sf)) # match CRS
population <- st_make_valid(population) # make valid
```

import major roads

```{r}
library(osmdata)

highways_pa <- opq(bbox = c(-80.52, 39.72, -74.70, 42.27)) |>
  add_osm_feature(key = 'highway', value = c('motorway')) |>
  osmdata_sf()
```

coverage gap analysis

```{r}
library(dplyr)

buffers <- st_buffer(stations_sf, dist = 16093) # 10 mile buffer

coverage_area <- st_make_valid(st_union(buffers)) # eliminate overlapping buffers

uncovered <- st_make_valid(st_difference(st_union(st_geometry(population)), coverage_area)) # uncovered area
```

visualize covered/uncovered areas

```{r}
ggplot() +
  geom_sf(data = population, fill = "white", color = "gray") +
  geom_sf(data = coverage_area, fill = "green", color = NA, alpha = 0.3) +
  geom_sf(data = uncovered, fill = "red", color = NA, alpha = 0.4) +
    coord_sf(xlim = c(-81, -74.25), ylim = c(39.25, 42.5), expand = FALSE) +
  ggtitle("Pennsylvania EV Station Coverage (10 Mile Convenience)") +
  labs(subtitle = "Areas in green are within 10 miles of an EV station")

ggsave("outputs/coverage_maps/ev_station_coverage_1.png")
```

incorporate population density information

```{r}
library(scales)

population <- population |>
  mutate(area_mi2 = as.numeric(st_area(geometry)) / 2.59e6,
         pop_density = estimate / area_mi2)

ggplot() +
  geom_sf(data = population, aes(fill = pop_density), color = "white", size = 0.2) +
  scale_fill_viridis_c(option = "viridis", 
                       trans = "log",
                       limits = c(10, 10000),
                       breaks = c(10, 100, 1000, 10000),
                       labels = label_comma(accuracy = 1),
                       name = bquote("Population Density (people/mi"^2*")")) +
  geom_sf(data = st_boundary(coverage_area), color = "magenta", alpha = 1, size = 1.5) +
#  geom_sf(data = uncovered, fill = "red", color = NA, alpha = 0.2) +
  coord_sf(xlim = c(-81, -74.25), ylim = c(39.25, 42.5), expand = FALSE) +
  ggtitle("Pennsylvania EV Station Coverage (10 Mile Convenience)") +
  labs(subtitle = "Areas in the magenta boundaries are within 10 miles of an EV station")

ggsave("outputs/coverage_maps_with_population/ev_station_coverage_population_pa_10mi.png")
```























